# Generated by Django 5.0.6 on 2025-09-07 12:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_company', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDamage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_QTYs_Damaged_by_WH', models.IntegerField(blank=True, null=True)),
                ('Number_of_Damaged_during_receiving', models.IntegerField(blank=True, null=True)),
                ('Total_Araive_Damaged', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='damages', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerExpiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('total_SKUs_expired', models.IntegerField(blank=True, null=True)),
                ('total_expired_SKUS_disposed', models.IntegerField(blank=True, null=True)),
                ('nearly_expired_1_to_3_months', models.IntegerField(blank=True, null=True)),
                ('nearly_expired_3_to_6_months', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expiries', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerHSE',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_Incidents_on_the_side', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hses', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10)),
                ('number_of_vehicles_daily', models.IntegerField(blank=True, null=True)),
                ('number_of_pallets', models.IntegerField(blank=True, null=True)),
                ('bulk', models.IntegerField(blank=True, null=True)),
                ('loose', models.IntegerField(blank=True, null=True)),
                ('cold', models.IntegerField(blank=True, null=True)),
                ('frozen', models.IntegerField(blank=True, null=True)),
                ('ambient', models.IntegerField(blank=True, null=True)),
                ('pending_shipments', models.IntegerField(blank=True, null=True)),
                ('number_of_shipments', models.IntegerField(blank=True, null=True)),
                ('total_quantity', models.IntegerField(blank=True, null=True)),
                ('number_of_line', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbounds', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_Locations_match', models.IntegerField(blank=True, null=True)),
                ('Total_Locations_not_match', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventories', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPalletLocationAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('Total_Storage_Pallet', models.IntegerField(blank=True, null=True)),
                ('Total_Storage_pallet_empty', models.IntegerField(blank=True, null=True)),
                ('Total_occupied_pallet_location', models.IntegerField(blank=True, null=True)),
                ('Total_Storage_Bin', models.IntegerField(blank=True, null=True)),
                ('Total_Storage_Bin_empty', models.IntegerField(blank=True, null=True)),
                ('Total_occupied_Bin_location', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pallet_location_availabilities', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerReturns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('total_orders_items_returned', models.IntegerField(blank=True, null=True)),
                ('number_of_return_items_orders_updated_on_time', models.IntegerField(blank=True, null=True)),
                ('number_of_return_items_orders_updated_late', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='returns', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerTransportationOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('released_order', models.IntegerField(blank=True, null=True)),
                ('pending_pick_orders', models.IntegerField(blank=True, null=True)),
                ('piked_order', models.IntegerField(blank=True, null=True)),
                ('number_of_PODs_collected_on_time', models.IntegerField(blank=True, null=True)),
                ('number_of_PODs_collected_Late', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outbounds', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerWHOutbound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20)),
                ('released_order', models.IntegerField(blank=True, null=True)),
                ('pending_pick_orders', models.IntegerField(blank=True, null=True)),
                ('piked_order', models.IntegerField(blank=True, null=True)),
                ('number_of_PODs_collected_on_time', models.IntegerField(blank=True, null=True)),
                ('number_of_PODs_collected_Late', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wh_outbounds', to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('customer', 'Customer'), ('employee', 'Employee')], max_length=20)),
                ('company', models.ManyToManyField(related_name='employees', to='customer.customer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UploadedExcelData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('shipment_number', models.CharField(max_length=100)),
                ('data', models.JSONField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('date', 'shipment_number')},
            },
        ),
    ]
