# Generated by Django 5.0.6 on 2025-09-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_alter_customerdamage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdamage',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerdamage',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerexpiry',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerexpiry',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerhse',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerhse',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinbound',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='customerinbound',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerinventory',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerinventory',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerpalletlocationavailability',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerpalletlocationavailability',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerreturns',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerreturns',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customertransportationoutbound',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customertransportationoutbound',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customerwhoutbound',
            name='assigned_day',
            field=models.CharField(blank=True, choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Sunday', 'Sunday')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='customerwhoutbound',
            name='time',
            field=models.DateField(blank=True, null=True),
        ),
    ]
