# Generated by Django 5.0.6 on 2025-09-09 13:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_alter_customerdamage_assigned_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerpalletlocationavailability',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pallet_location_availability', to='customer.customer'),
            preserve_default=False,
        ),
    ]
