# Generated by Django 5.0.6 on 2025-09-09 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customerpalletlocationavailability_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerpalletlocationavailability',
            name='company',
        ),
    ]
