# Generated by Django 5.2.7 on 2026-05-13 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0029_picker_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productivitydashboard',
            name='banner_text',
            field=models.TextField(blank=True, help_text='Supporting text under the banner title (white text on black bar).', verbose_name='Banner text'),
        ),
        migrations.AlterField(
            model_name='productivitydashboard',
            name='banner_title',
            field=models.CharField(blank=True, help_text='Headline inside the black bar (e.g. Overtime Cap Rule).', max_length=255, verbose_name='Banner title'),
        ),
        migrations.AlterField(
            model_name='productivitydashboard',
            name='banner_value',
            field=models.CharField(blank=True, help_text='Right side of the bar, large accent (e.g. 150 hrs).', max_length=120, verbose_name='Banner value'),
        ),
        migrations.AlterField(
            model_name='productivitydashboard',
            name='dashboard_title',
            field=models.CharField(default='Productivity Dashboard', help_text='Main headline after “MODULE” (e.g. Productivity Dashboard).', max_length=255, verbose_name='Dashboard title'),
        ),
        migrations.AlterField(
            model_name='productivitydashboard',
            name='intro_text',
            field=models.TextField(blank=True, help_text='Optional paragraph under the main title and above the black banner.', verbose_name='Intro text (optional)'),
        ),
        migrations.AlterField(
            model_name='productivitydashboard',
            name='module_number',
            field=models.CharField(default='01', help_text='Large number on the left (e.g. 01).', max_length=16, verbose_name='Module number'),
        ),
        migrations.AlterField(
            model_name='productivitydashboardcard',
            name='card_text',
            field=models.TextField(help_text='Body under the card title.', verbose_name='Card text'),
        ),
        migrations.AlterField(
            model_name='productivitydashboardcard',
            name='card_title',
            field=models.CharField(help_text='Small caps line under the icon (e.g. Overtime reduction).', max_length=255, verbose_name='Card title'),
        ),
        migrations.AlterField(
            model_name='productivitydashboardcard',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Only when icon is “Uploaded image”.', null=True, upload_to='productivity/card_icons/', verbose_name='Custom icon image'),
        ),
        migrations.AlterField(
            model_name='productivitydashboardcard',
            name='icon_kind',
            field=models.CharField(choices=[('red_ot', 'Red arrow + OT'), ('green_out', 'Green arrow + OUT'), ('bell', 'Bell'), ('stop', 'Stop / cap bar'), ('image', 'Uploaded image')], default='bell', max_length=16, verbose_name='Icon'),
        ),
    ]
