# Generated by Django 5.2.7 on 2026-05-13 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0030_alter_productivitydashboard_banner_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='barrierchallenge',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Barrier challenge', 'verbose_name_plural': '[Tab 1 — Zone plan] Barrier challenges'},
        ),
        migrations.AlterModelOptions(
            name='barrierprogram',
            options={'ordering': ('-updated_at',), 'verbose_name': '[Tab 1 — Zone plan] Barrier program', 'verbose_name_plural': '[Tab 1 — Zone plan] Barrier programs'},
        ),
        migrations.AlterModelOptions(
            name='pickerperformanceprogram',
            options={'ordering': ('-updated_at',), 'verbose_name': '[Tab 2 — Picker performance] Program', 'verbose_name_plural': '[Tab 2 — Picker performance] Programs'},
        ),
        migrations.AlterModelOptions(
            name='pickershiftrecord',
            options={'ordering': ('work_date', 'picker_name', 'id'), 'verbose_name': '[Tab 2 — Picker performance] Shift record', 'verbose_name_plural': '[Tab 2 — Picker performance] Shift records'},
        ),
        migrations.AlterModelOptions(
            name='pickingmethodphase',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Picking method phase (week)', 'verbose_name_plural': '[Tab 1 — Zone plan] Picking method phases'},
        ),
        migrations.AlterModelOptions(
            name='pickingmethodphasetag',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Phase tag', 'verbose_name_plural': '[Tab 1 — Zone plan] Phase tags'},
        ),
        migrations.AlterModelOptions(
            name='pickingmethodprogram',
            options={'ordering': ('-updated_at',), 'verbose_name': '[Tab 1 — Zone plan] Picking method program', 'verbose_name_plural': '[Tab 1 — Zone plan] Picking method programs'},
        ),
        migrations.AlterModelOptions(
            name='pickingmethodsummarycard',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Picking method summary card', 'verbose_name_plural': '[Tab 1 — Zone plan] Picking method summary cards'},
        ),
        migrations.AlterModelOptions(
            name='processimprovementitem',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Process improvement item', 'verbose_name_plural': '[Tab 1 — Zone plan] Process improvement items'},
        ),
        migrations.AlterModelOptions(
            name='processimprovementprogram',
            options={'ordering': ('-updated_at',), 'verbose_name': '[Tab 1 — Zone plan] Process improvement program', 'verbose_name_plural': '[Tab 1 — Zone plan] Process improvement programs'},
        ),
        migrations.AlterModelOptions(
            name='productivitydashboard',
            options={'ordering': ('-updated_at',), 'verbose_name': '[Tab 1 — Zone plan] Productivity dashboard', 'verbose_name_plural': '[Tab 1 — Zone plan] Productivity dashboards'},
        ),
        migrations.AlterModelOptions(
            name='productivitydashboardcard',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Productivity dashboard card', 'verbose_name_plural': '[Tab 1 — Zone plan] Productivity dashboard cards'},
        ),
        migrations.AlterModelOptions(
            name='rolloutplancard',
            options={'ordering': ('sort_order', 'id'), 'verbose_name': '[Tab 1 — Zone plan] Rollout plan card', 'verbose_name_plural': '[Tab 1 — Zone plan] Rollout plan cards'},
        ),
        migrations.AlterModelOptions(
            name='rolloutprogram',
            options={'ordering': ('-updated_at',), 'verbose_name': '[Tab 1 — Zone plan] Rollout program', 'verbose_name_plural': '[Tab 1 — Zone plan] Rollout programs'},
        ),
    ]
