# Generated by Django 5.2.7 on 2026-05-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0032_dashboardworkbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickerperformanceprogram',
            name='excel_sheet_name',
            field=models.CharField(default='Sheet1', help_text='Sheet to read on import (use Sheet1 for OCT 30.xlsx). If the saved name is missing, import tries Sheet1 when present. Single-sheet workbooks always use that tab.', max_length=64, verbose_name='Excel sheet name'),
        ),
    ]
