# Generated by Django 5.2.7 on 2026-07-01 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0033_picker_perf_sheet_default_oct30'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pickershiftrecord',
            options={'ordering': ('work_date', 'picker_name', 'id'), 'verbose_name': '[Tab 2 — Picker performance] Line record', 'verbose_name_plural': '[Tab 2 — Picker performance] Line records'},
        ),
        migrations.AddField(
            model_name='pickershiftrecord',
            name='delivery_number',
            field=models.CharField(blank=True, default='', max_length=64, verbose_name='Delivery number'),
        ),
        migrations.AddField(
            model_name='pickershiftrecord',
            name='is_pick',
            field=models.BooleanField(default=False, help_text='True when Source Storage Bin starts with "PICK".', verbose_name='Is PICK'),
        ),
        migrations.AddField(
            model_name='pickershiftrecord',
            name='pick_duration_min',
            field=models.FloatField(blank=True, help_text='(Confirmation − Creation) in minutes.', null=True, verbose_name='Pick duration (min)'),
        ),
        migrations.AlterField(
            model_name='pickerperformanceprogram',
            name='excel_sheet_name',
            field=models.CharField(default='SAP', help_text='Sheet to read on import (use SAP for PICKING_.xlsx). If the saved name is missing, import tries SAP when present.', max_length=64, verbose_name='Excel sheet name'),
        ),
        migrations.AlterField(
            model_name='pickershiftrecord',
            name='lines',
            field=models.PositiveSmallIntegerField(default=1, help_text='Always 1 per SAP row (one row = one line).', verbose_name='Lines'),
        ),
        migrations.AlterField(
            model_name='pickershiftrecord',
            name='shift_band',
            field=models.CharField(choices=[('S1', 'Shift 1 (06:00–15:00)'), ('S2', 'Shift 2 (15:00–00:00)'), ('S3', 'Shift 3 (00:00–06:00)'), ('MORNING', 'Morning (legacy)'), ('EVENING', 'Evening / night (legacy)'), ('OTHER', 'Other / unknown')], default='OTHER', help_text='S1/S2/S3 from Confirmation time.', max_length=16, verbose_name='Shift'),
        ),
        migrations.AlterField(
            model_name='pickershiftrecord',
            name='work_date',
            field=models.DateField(blank=True, help_text='Confirmation date (required for trends and weekday KPIs).', null=True, verbose_name='Date'),
        ),
    ]
