# Generated by Django 5.0.6 on 2026-09-24 06:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_delete_hierarchicalgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundShipmentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipment_key', models.CharField(max_length=200, unique=True)),
                ('company', models.CharField(blank=True, max_length=64)),
                ('shipment_nbr', models.CharField(blank=True, max_length=80)),
                ('warehouse', models.CharField(blank=True, max_length=80)),
                ('proposed_result', models.CharField(blank=True, max_length=8)),
                ('proposed_reason', models.TextField(blank=True)),
                ('approved_result', models.CharField(blank=True, max_length=8)),
                ('approved_reason', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_reviews_decided', to=settings.AUTH_USER_MODEL)),
                ('submitted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_reviews_submitted', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
